name: torus
channels:
  - defaults
dependencies:
  - pip:
    - build==0.7.0
    - bump==1.3.0
    - twine == 3.5.0
    - numpy==1.21.3
    - pynput==1.7.4
    - pytest==6.2.5
    - torus-engine>=0.1.0